repos:
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: uv run mypy .
        additional_dependencies: [mypy]
        types: [python]
        language: python
        pass_filenames: false
