repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: uv run mypy .
        types: [python]
        language: system
        pass_filenames: false
