repos:
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
