repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff-format
        exclude: ^uv\.lock$
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^uv\.lock$
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: uv run mypy .
        additional_dependencies: [mypy]
        types: [python]
        language: python
        pass_filenames: false
