src = ["src"]

# Use Ruff for sorting imports
lint.extend-select = ["I"]

[lint.per-file-ignores]
# Do not enforce usage and import order rules in init files
"__init__.py" = ["E402", "F401", "I"]

# Allow wild imports in conftest
"tests/conftest.py" = ["F405", "E402", "F403"]