site_name: raggy
site_description: 'A R.A.G toolkit'
site_url: https://zzstoatzz.github.io/raggy/
docs_dir: docs
repo_url: https://github.com/zzstoatzz/raggy

nav:
  - Docs:
    - Getting started:
      - Installation: welcome/installation.md
      - Tutorial: welcome/tutorial.md
    - Ingest:
      - Strategy: ingest_strategy.md

  - API reference:
    - Home:
      - raggy: api_reference/index.md
    - Loaders:
      - raggy.loaders.base: api_reference/loaders/base.md
      - raggy.loaders.github: api_reference/loaders/github.md
      - raggy.loaders.pdf: api_reference/loaders/pdf.md
      - raggy.loaders.web: api_reference/loaders/web.md
    - Vectorstores:
      - raggy.vectorstores.base: api_reference/vectorstores/base.md
      - raggy.vectorstores.chroma: api_reference/vectorstores/chroma.md
      - raggy.vectorstores.tpuf: api_reference/vectorstores/tpuf.md
    - Settings:
      - raggy.settings: api_reference/settings.md
    - Utilities:
      - raggy.utilities.asyncutils: api_reference/utilities/asyncutils.md
      - raggy.utilities.collections: api_reference/utilities/collections.md
      - raggy.utilities.embeddings: api_reference/utilities/embeddings.md
      - raggy.utilities.filesystem: api_reference/utilities/filesystem.md
      - raggy.utilities.ids: api_reference/utilities/ids.md
      - raggy.utilities.logging: api_reference/utilities/logging.md
      - raggy.utilities.text: api_reference/utilities/text.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    primary: green
    accent: teal
  name: material
  logo: assets/logos/raggy.png
  favicon: assets/logos/raggy.png

plugins:
  - search
  - markdownextradata
  - social:
      cards_layout_options:
        font_family: Inter
        # background_color: "#2d6df6"
        background_color: "#181544"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: false
            show_bases: false
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            show_signature: false
            heading_level: 2
            filters: ["!^_"]
          import:
          - https://docs.python-requests.org/en/master/objects.inv
watch:
  - src
  - docs
  - mkdocs.yml

hooks:
  - docs/hooks.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.emoji:
  - toc:
      permalink: true
      title: On this page
      

extra:
  get_started: welcome/what_is_raggy
  hero:
    title: 'raggy'
    description: 'a R.A.G toolkit'
  announcement:
    title: "so you want to do R.A.G?"
    url: https://github.com/zzstoatzz/raggy/releases/tag/v0.2.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/raggy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Nathan_Nowack