site_name: raggy
site_description: "A R.A.G toolkit"
site_url: https://zzstoatzz.github.io/raggy/
docs_dir: docs
repo_url: https://github.com/zzstoatzz/raggy

nav:
  - Home: index.md
  - Getting Started:
      - Installation: welcome/installation.md
      - Tutorial: welcome/tutorial.md
  - Examples: examples/index.md
  - Contributing: contributing.md
  - Ingest Strategy: ingest_strategy.md
  - API Reference:
      - Overview: api_reference/index.md
      - Loaders:
          - Base: api_reference/loaders/base.md
          - GitHub: api_reference/loaders/github.md
          - PDF: api_reference/loaders/pdf.md
          - Web: api_reference/loaders/web.md
      - Vectorstores:
          - Base: api_reference/vectorstores/base.md
          - Chroma: api_reference/vectorstores/chroma.md
          - TurboPuffer: api_reference/vectorstores/tpuf.md
      - Settings: api_reference/settings.md
      - Utilities:
          - Async: api_reference/utilities/asyncutils.md
          - Collections: api_reference/utilities/collections.md
          - Embeddings: api_reference/utilities/embeddings.md
          - Filesystem: api_reference/utilities/filesystem.md
          - IDs: api_reference/utilities/ids.md
          - Logging: api_reference/utilities/logging.md
          - Text: api_reference/utilities/text.md

theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - announce.dismiss
  palette:
    primary: green
    accent: teal
  name: material
  logo: assets/logos/raggy.png
  favicon: assets/logos/raggy.png
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - markdownextradata
  - social:
      cards_layout_options:
        font_family: Inter
        background_color: "#181544"
  - awesome-pages
  - autolinks
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: false
            show_bases: false
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            show_signature: false
            heading_level: 2
            filters: ["!^_"]
          import:
            - https://docs.python-requests.org/en/master/objects.inv

watch:
  - src
  - docs
  - mkdocs.yml

hooks:
  - docs/hooks.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.emoji:
  - toc:
      permalink: true
      title: On this page

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zzstoatzz/raggy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Nathan_Nowack
  version:
    provider: mike
  generator: false
  homepage: https://zzstoatzz.github.io/raggy
  announcement:
    text: "New in 0.2.0: Simplified vectorstore operations"
    link: https://github.com/zzstoatzz/raggy/releases/tag/v0.2.0
